#!/bin/bash
make -C modules init
export TRAVIS_BUILD_NUMBER=10
sudo docker build --cache-from sysporter:deps --target deps -t sysporter:deps .
sudo docker build --build-arg TRAVIS_BUILD_NUMBER --cache-from sysporter:deps --cache-from sysporter:builder --target builder -t sysporter:builder .
sudo docker build --cache-from sysporter:deps --cache-from sysporter:builder --cache-from sysporter:runtime --target runtime -t sysporter:runtime .
sudo docker build --cache-from sysporter:deps --cache-from sysporter:builder --cache-from sysporter:runtime --cache-from sysporter:testing --target testing -t sysporter:testing .
