#!/bin/bash
#
# Copyright (C) 2019 IBM Corporation.
#
# Authors:
# Frederico Araujo <frederico.araujo@ibm.com>
# Teryl Taylor <terylt@ibm.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

make -C modules init
export TRAVIS_BUILD_NUMBER=10
sudo docker build --cache-from sf-a1.9.1-0.26.4:deps --target deps -t sf-a1.9.1-0.26.4:deps .
sudo docker build --build-arg TRAVIS_BUILD_NUMBER --cache-from sf-a1.9.1-0.26.4:deps --cache-from sf-a1.9.1-0.26.4:builder --target builder -t sf-a1.9.1-0.26.4:builder .
sudo docker build --cache-from sf-a1.9.1-0.26.4:deps --cache-from sf-a1.9.1-0.26.4:builder --cache-from sf-a1.9.1-0.26.4:runtime --target runtime -t sf-a1.9.1-0.26.4:runtime .
sudo docker build --cache-from sf-a1.9.1-0.26.4:deps --cache-from sf-a1.9.1-0.26.4:builder --cache-from sf-a1.9.1-0.26.4:runtime --cache-from sf-a1.9.1-0.26.4:testing --target testing -t sf-a1.9.1-0.26.4:testing .
