# syntax = docker/dockerfile:1.0-experimental
#
# Copyright (C) 2019 IBM Corporation.
#
# Authors:
# Frederico Araujo <frederico.araujo@ibm.com>
# Teryl Taylor <terylt@ibm.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#-----------------------
# Usage
#-----------------------
#
# 1. Build with Docker BuildKit:
#
#    DOCKER_BUILDKIT=1 docker build --no-cache \
#                                   --build-arg UBI_VER=8.4-206
#                                   --target mods \
#                                   -t ubi:mods-0.0.0 \
#                                   -f Dockerfile.ubi.amd64 .
#

#-----------------------
# Stage: base
#-----------------------
ARG UBI_VER
FROM registry.access.redhat.com/ubi8/ubi:${UBI_VER} AS base

# Install Packages
COPY ./scripts/installUBIDependencyWoSubManager.sh /build/install.sh
RUN ( /build/install.sh base ) && rm -rf /build

#-----------------------
# Stage: mods
#-----------------------
FROM base AS mods

# environment and args
ARG INSTALL_PATH=/usr/local/sysflow

ENV PATH="$PATH:"${INSTALL_PATH}"/modules/bin"

ENV LIBRARY_PATH=/lib64

ENV HOST_ROOT=/host

ENV HOME=/root

#  build modules
COPY ./modules /build/modules
COPY ./makefile.* /build/
COPY ./docker-entry-ubi.sh /usr/local/sysflow/modules/bin/
RUN  dnf -y install git && \
     cd /build/modules && \
     make INSTALL_PATH=${INSTALL_PATH} install && \
     mkdir /falcosrc && cp -a /usr/src/falco-* /falcosrc/ && \
     make clean && rm -rf /build/modules && \
     dnf -y remove git && dnf -y clean all && rm -rf /var/cache/dnf

ENTRYPOINT ["/usr/local/sysflow/modules/bin/docker-entry-ubi.sh"]
