# Copyright (C) 2022 IBM Corporation.
#
# Authors:
# Frederico Araujo <frederico.araujo@ibm.com>
# Teryl Taylor <terylt@ibm.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

SYSFLOW_VERSION?=0.6.3
SYSFLOW_BUILD_NUMBER?=1
FALCO_VERSION=0.36.2
FALCO_LIBS_VERSION=0.13.4
FALCO_LIBS_DRIVER_VERSION=6.0.1+driver
AVRO_VERSION=release-1.11.0
ELF_VERSION=v0.189
GLOG_VERSION=v0.6.0
SNAPPY_VERSION=1.1.9
DKMS_VERSION=v3.0.3
GHCFS_VERSION=v1.5.14
XXHASH_VERSION=v0.8.2
SPARSE_VERSION=sparsehash-2.0.4
ALPINE_VERSION=3.18.3
UBI_VERSION=9.3-1552
