#
# Copyright (C) 2019 IBM Corporation.
#
# Authors:
# Frederico Araujo <frederico.araujo@ibm.com>
# Teryl Taylor <terylt@ibm.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PREFIX=/usr/local/sysflow
MODPREFIX=$(PREFIX)/modules
LIBPREFIX=$(MODPREFIX)/lib
BINPREFIX=$(MODPREFIX)/bin
DRIVERPREFIX=/usr/src/sysdig-
SDINCPREFIX=$(MODPREFIX)/include/sysdig
AVRINCPREFIX=$(MODPREFIX)/include/avro
