#
# Copyright (C) 2019 IBM Corporation.
#
# Authors:
# Frederico Araujo <frederico.araujo@ibm.com>
# Teryl Taylor <terylt@ibm.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

SYSFLOW_VERSION?=0.5.0
SYSFLOW_BUILD_NUMBER?=1
FALCO_VERSION=0.32.0
FALCO_LIBS_VERSION=39ae7d40496793cf3d3e7890c9bbdc202263836b
FALCO_LIBS_CHECKSUM=SHA256=2cf44f06a282e8cee7aa1f775a08ea94c06e275faaf0636b21eb06af28cf4b3f
FALCO_LIBS_DRIVER_VERSION=39ae7d40496793cf3d3e7890c9bbdc202263836b
AVRO_VERSION=release-1.11.0
ELFUTILS_VERSION=elfutils-0.173
GLOG_VERSION=v0.5.0
SNAPPY_VERSION=1.1.9
DKMS_VERSION=v3.0.3
UBI_VERSION=8.6-754.1655117782
