#!/bin/bash
set -e

if command -v hostname &> /dev/null
then
    export HOSTNAME=$(hostname)
    if command -v awk &> /dev/null
    then
        export NODE_IP=$(hostname -I | awk '{print $1}')
    fi
fi

export HOME=/run/sysflow
if [ "${DRIVER_TYPE}" == "ebpf-core" ] || [ -z "${DRIVER_TYPE}" ]; then
	/etc/sysflow/driver/falcoctl driver config --type modern_ebpf
elif [ "${DRIVER_TYPE}" == "ebpf" ]; then
    export DRIVER_TYPE="ebpf"
    if [ -z "${FALCO_BPF_PROBE}" ]; then
       export FALCO_BPF_PROBE=""
    fi
else
	/etc/sysflow/driver/falcoctl driver config --type ${DRIVER_TYPE}
fi
/etc/sysflow/driver/falcoctl driver install --compile=true --download=true
/usr/bin/sysporter -e ${NODE_ID:-${HOSTNAME}} -u ${SOCKET:-/sock/sysflow.sock} ${DRIVER_TYPE:+-k} "${DRIVER_TYPE}"  ${FILTER:+-f "$FILTER"}
