#!/bin/bash
set -e

if command -v hostname &> /dev/null
then
    export HOSTNAME=$(hostname)
    if command -v awk &> /dev/null
    then
        export NODE_IP=$(hostname -I | awk '{print $1}')
    fi
fi

export HOME=/run/sysflow
if [ "${DRIVER_TYPE}" == "ebpf" ] || [ -z "${DRIVER_TYPE}" ]; then
    export DRIVER_TYPE="ebpf"
    if [ -z "${FALCO_BPF_PROBE}" ]; then
       export FALCO_BPF_PROBE=""
    fi
    /etc/sysflow/driver/falco-driver-loader bpf ${DRIVER_OPTS}
elif [ "${DRIVER_TYPE}" == "kmod" ]; then
    /etc/sysflow/driver/falco-driver-loader module ${DRIVER_OPTS}
fi
/usr/bin/sysporter -e ${NODE_ID:-${HOSTNAME}} -u ${SOCKET:-/sock/sysflow.sock} ${DRIVER_TYPE:+-k} "${DRIVER_TYPE}"  ${FILTER:+-f "$FILTER"}
