#
# Copyright (C) 2022 IBM Corporation.
#
# Authors:
# Frederico Araujo <frederico.araujo@ibm.com>
# Teryl Taylor <terylt@ibm.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG FALCO_LIBS_VER
ARG FALCO_VER
ARG UBI_VER
ARG ALPINE_VER
ARG ALPINE_IMAGE
ARG RUNTIME_IMAGE

#-----------------------
# Stage: Builder
#-----------------------
FROM ${ALPINE_IMAGE}:${ALPINE_VER} AS builder

ARG ARCH="x86_64"

# sysflow release
ARG SYSFLOW_VERSION

# setup build requirements
RUN apk add \
	make \
	g++ \
	boost-dev \
	boost-static \
        zstd-static \
	flex \
	bison \
	gawk \
	sparsehash

# install libsysflow
COPY libsysflow-musl-${SYSFLOW_VERSION}-${ARCH}.tar.gz .
RUN tar xzf libsysflow-musl-${SYSFLOW_VERSION}-${ARCH}.tar.gz && cp -r libsysflow-musl-${SYSFLOW_VERSION}-${ARCH}/usr/* /usr/.

# build the example program
COPY callback.cpp /build/
COPY Makefile /build/
COPY manifest /build/
RUN MUSL=1 make -C /build install

#-----------------------
# Stage: Runtime
#-----------------------
FROM sysflowtelemetry/${RUNTIME_IMAGE}:driver-${FALCO_LIBS_VER}-${FALCO_VER}-${UBI_VER} AS runtime

COPY --from=builder /usr/local/example/bin/callback /usr/local/example/bin/callback

ARG driver_type="e"
ENV DRIVER_TYPE=$driver_type

CMD /usr/local/example/bin/callback ${DRIVER_TYPE}

