#!/bin/bash

echo "[***] Build hook running"

# Initialize submodules
make -C modules init

# Multi-stage build with caching from intermediate stages
docker build \
    --cache-from $DOCKER_REPO:deps \
    --target deps \
    -t $DOCKER_REPO:deps .

docker build \
    --build-arg COMMIT=$(git rev-parse --short HEAD) \
    --cache-from $DOCKER_REPO:deps \
    --cache-from $DOCKER_REPO:builder \
    --target builder \
    -t $DOCKER_REPO:builder .

docker build \
    --cache-from $DOCKER_REPO:deps \
    --cache-from $DOCKER_REPO:builder \
    --cache-from $IMAGE_NAME \
    --target runtime \
    -t $IMAGE_NAME .
